[package]
name = "carbon"
version = "0.0.0"
authors = ["wang4615 <wang.juny@husky.neu.edu>"]

[dependencies]
nix = "0.7.0"
ansi_term = "0.9.0"
regex = "0.2"
chrono = "0.3"
fnv = "1.0.3"
httparse = "1.2.2"